language: dart
dart:
  # Install the latest stable release
  - "2.1.1"
dart_task:
  - test: --exclude-tags no-xvfb
    xvfb: false
script:
  - pub run test test/mqtt_client_base_test.dart
  - pub run test test/mqtt_client_message_test.dart
  - pub run test test/mqtt_client_management_test.dart
  - pub run test test/mqtt_client_publishing_manager_test.dart
  - pub run test test/mqtt_client_subscription_manager_test.dart
  - pub run test test/mqtt_client_connection_unsecure_test.dart
  - pub run test test/mqtt_client_connection_secure_test.dart
  - pub run test test/mqtt_client_connection_ws_test.dart
branches:
    only:
    - master

