name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 10.8.1
repository: https://github.com/shamblett/mqtt_client
homepage: https://github.com/shamblett/mqtt_client

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  typed_data: '^1.4.0'
  event_bus: '^2.0.1'
  path: '^1.9.1'
  crypto: '^3.0.6'
  meta: '^1.16.0'
  web: '>=0.5.0 <2.0.0'
  characters: '^1.4.0'

dev_dependencies:
  test: '^1.25.14'
  lints: '^6.0.0'
  build_runner: '^2.4.14'
  build_test: '^2.2.3'
  build_web_compilers: '^4.1.0'
  mocktail: '^1.0.4'
  http: '^1.2.2'
  aws_signature_v4: '^0.6.3'
  aws_common: '^0.7.4'
  dart_code_metrics_presets: '^2.21.0'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key

topics:
  - iot
  - chat
  - mqtt
  - data

screenshots:
    - description: 'MQTT Specification'
      path: example/screenshots/mqtt-ver.webp
    - description: 'MQTT IOT Usage'
      path: example/screenshots/MQTT-1.webp