name: mqtt_client
description: A server side MQTT client for Dart supporting both secure sockets and websockets.
version: 5.5.2
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/mqtt_client

environment:
 sdk: ">=2.0.0-dev  <3.0.0"

dependencies:
 typed_data: '^1.1.6'
 meta: '^1.0.4'
 event_bus: '^1.0.1'
 path: '^1.6.2'
 crypto: '^2.0.6' 

dev_dependencies:
 test: '^1.3.0'
 coverage: '^0.12.3'
 dart_dev: '^2.0.1'
 dart_style: '^1.1.3'
 mockito: '^3.0.0'

