name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 9.6.9
homepage: https://github.com/shamblett/mqtt_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  typed_data: '^1.3.1'
  event_bus: '^2.0.0'
  path: '^1.8.2'
  crypto: '^3.0.2'
  meta: '^1.8.0'

dev_dependencies:
  test: '^1.21.2'
  mockito: '^5.2.0'
  lints: '^2.0.0'
  build_runner: '^2.1.11'
  build_test: '^2.1.5'
  build_web_compilers: '^3.2.3'
  http: '^0.13.4'
  sigv4: '^5.0.0'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key
