name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 10.0.1
repository: https://github.com/shamblett/mqtt_client
homepage: https://github.com/shamblett/mqtt_client

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  typed_data: '^1.3.2'
  event_bus: '^2.0.0'
  path: '^1.8.2'
  crypto: '^3.0.3'
  meta: '^1.9.1'

dev_dependencies:
  test: '^1.25.0'
  lints: '^3.0.0'
  build_runner: '^2.4.4'
  build_test: '^2.2.2'
  build_web_compilers: '^4.0.3'
  http: '^0.13.6'
  sigv4: '^5.0.0'
  mocktail: '^1.0.2'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key
