name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 8.3.0
homepage: https://github.com/shamblett/mqtt_client

environment:
 sdk: ">=2.0.0 <3.0.0"

dependencies:
 typed_data: '^1.1.6'
 event_bus: '^1.1.1'
 path: '^1.6.4'
 crypto: '^2.1.3'
 meta: '^1.1.8'

dev_dependencies:
 test: '^1.14.7'
 mockito: '^4.1.1'
 pedantic: '^1.9.0'
 pana: '^0.13.5'
 build_runner: '^1.8.0'
 build_test: '^1.2.0'
 build_web_compilers: '^2.8.0'





